### ISSUE TITLE
The app doesn't prompt the user to grant write permission when using the Export feature

### ISSUE THREAD

**Issue by ditokp** [RodrigoDavy/PixelArtist#24]
Hello, in my device I can't export the image. It says that the app doesn't have write permission. How to add this permission?

My device spec:
Advan i4D
Android Lollipop

**Comment by RodrigoDavy** [comment]
I apologize, this is a bug in the app (it should prompt you to concede permission either when installing the app or when using the Export function depending on your Android version)

As a workaround, you can go on Settings -> Device -> Applications (or maybe 'Apps') -> Pixel Artist -> Permissions. There you'll find the option to grant write permission to the app. The way to get there might be a little different depending on the flavour of your phone manufacturer

I'll try to look into this ASAP, but it might take a while. Thanks for the report!

**Comment by RodrigoDavy** [comment]
It's actually a pretty dumb mistake, I probably should just implement what's described on this page: https://developer.android.com/training/permissions/requesting

I'm gonna be without a computer for a few days, so it might take a while. If anyone wants to give it a shot, it seems like an easy one for someone with some basic experience with Android development

**Comment by pstn** [comment]
I manually gave Pixel Artist storage permissions on my phone, however the problem persists. I can't export images because I get the write permission error. I also tried force closing the app and restarting it.

Can I be of any further assistance in debugging the issue?

I'm on lineageos 15.1 (Android 8.1)

**Comment by RodrigoDavy** [comment]
I checked it myself and I'm getting the same error on AOSP (Android 6.0). I'll be looking into this very soon, thanks for reporting it

**Comment by RodrigoDavy** [comment]
Ok, it was my mistake, the app was failing to check properly the write_permission. I (hopefully) fixed this bug and it should be updated on F-Droid in a few days
